#include "test.hpp"

void test_math();
void test_coords();
void test_terrain();
void test_wdl();
void test_blp();
void test_m2();
void test_m2_material();
void test_wmo();
void test_anim();
void test_proto();
void test_raster();
void test_editing();
void test_gizmo();
void test_bridge();
void test_db_export();
void test_debugdraw();
void test_modelmesh();
void test_clientfx();
void test_fxbridge();
void test_integration();
void test_dbc_defs();
void test_gridmap();
void test_navmesh();
void test_rhi();
void test_vmap();
void test_storage();
void test_world_sim();
void test_net();
void test_world_socket();
void test_minimap();
void test_movement();
void test_query();
void test_query_cache();
void test_chat();
void test_vendor_list();
void test_page_text();
void test_loot_response();
void test_text_emote();
void test_item_query();
void test_guild_query();
void test_quest_query();
void test_render();
void test_asset();
void test_placement_io();
void test_client_data();
void test_audio();
void test_world_view();
void test_picking();
void test_bounds();
void test_wmo_pick();
void test_client_version();
void test_dbc_index();
void test_wdl_mesh();
void test_frustum();
void test_liquid_color();
void test_tile_streamer();
void test_world_lod();
void test_world_pick();
void test_command_stack();
void test_dbc_schema();
void test_gridmap_writer();

int main() {
    test_math();
    test_coords();
    test_terrain();
    test_wdl();
    test_blp();
    test_m2();
    test_m2_material();
    test_wmo();
    test_anim();
    test_proto();
    test_raster();
    test_editing();
    test_gizmo();
    test_bridge();
    test_db_export();
    test_debugdraw();
    test_modelmesh();
    test_clientfx();
    test_fxbridge();
    test_integration();
    test_dbc_defs();
    test_gridmap();
    test_navmesh();
    test_rhi();
    test_vmap();
    test_storage();
    test_world_sim();
    test_net();
    test_world_socket();
    test_minimap();
    test_movement();
    test_query();
    test_query_cache();
    test_chat();
    test_vendor_list();
    test_page_text();
    test_loot_response();
    test_text_emote();
    test_item_query();
    test_guild_query();
    test_quest_query();
    test_render();
    test_asset();
    test_placement_io();
    test_client_data();
    test_audio();
    test_world_view();
    test_picking();
    test_bounds();
    test_wmo_pick();
    test_client_version();
    test_dbc_index();
    test_wdl_mesh();
    test_frustum();
    test_liquid_color();
    test_tile_streamer();
    test_world_lod();
    test_world_pick();
    test_command_stack();
    test_dbc_schema();
    test_gridmap_writer();

    std::printf("\n%d checks, %d failures\n", test::g_checks, test::g_failures);
    return test::g_failures == 0 ? 0 : 1;
}
